# Copyright (c) 2026, BuFf0k and contributors
# For license information, please see license.txt

import base64
import json
import re

import frappe

from frappe_sign.utils.audit import sha256_bytes
from frappe_sign.utils.files import get_file_bytes


PDF_DATA_URL_PATTERN = re.compile(r"^data:application/pdf;base64,(.+)$")


def decode_pdf_data_url(data_url):
    if not data_url:
        frappe.throw("Missing PDF data.")

    match = PDF_DATA_URL_PATTERN.match(data_url)

    if not match:
        frappe.throw("Only PDF files are supported.")

    try:
        pdf_bytes = base64.b64decode(match.group(1), validate=True)
    except Exception:
        frappe.throw("Could not decode uploaded PDF.")

    if not pdf_bytes.startswith(b"%PDF"):
        frappe.throw("Uploaded file does not appear to be a valid PDF.")

    return pdf_bytes


def validate_signed_pdf_bytes(pdf_bytes):
    uploaded_hash = sha256_bytes(pdf_bytes)

    match = find_request_by_document_hash(uploaded_hash)

    if not match:
        return {
            "valid": False,
            "status": "not_found",
            "uploaded_pdf_hash": uploaded_hash,
            "uploaded_document_type": "Unknown",
            "message": "The uploaded PDF does not match any signed document generated by this Frappe Sign instance.",
        }

    request = frappe.get_doc("Frappe Sign Request", match["request_name"])

    if match["document_type"] == "certificate_signed_pdf":
        document_check = verify_stored_certificate_signed_pdf(request, uploaded_hash)
    else:
        document_check = verify_stored_signed_pdf(request, uploaded_hash)

    audit_chain_check = verify_audit_chain(request.name)
    certificate_check = get_certificate_summary(request)

    valid = document_check["passed"] and audit_chain_check["passed"]

    return {
        "valid": valid,
        "status": "valid" if valid else "failed",
        "uploaded_pdf_hash": uploaded_hash,
        "uploaded_document_type": match["document_type"],
        "request": build_request_summary(request),
        "signers": build_signer_summary(request),
        "stored_pdf_check": document_check,
        "audit_chain_check": audit_chain_check,
        "certificate_check": certificate_check,
    }


def validate_signed_pdf_and_certificate_bytes(pdf_bytes, certificate_bytes):
    result = validate_signed_pdf_bytes(pdf_bytes)

    certificate_hash = sha256_bytes(certificate_bytes)

    result["uploaded_certificate_hash"] = certificate_hash

    if not result.get("request"):
        result["certificate_check"] = {
            "passed": False,
            "message": "The signed document could not be matched, so the certificate could not be validated.",
        }
        result["valid"] = False
        return result

    request = frappe.get_doc("Frappe Sign Request", result["request"]["name"])

    certificate_check = verify_certificate_bytes(request, certificate_hash)

    result["certificate_check"] = certificate_check
    result["valid"] = bool(result["valid"] and certificate_check["passed"])
    result["status"] = "valid" if result["valid"] else "failed"

    return result


def find_request_by_document_hash(pdf_hash):
    request_name = frappe.db.get_value(
        "Frappe Sign Request",
        {
            "signed_pdf_hash": pdf_hash,
        },
        "name",
    )

    if request_name:
        return {
            "request_name": request_name,
            "document_type": "signed_pdf",
            "matched_by": "Frappe Sign Request.signed_pdf_hash",
        }

    request_name = frappe.db.get_value(
        "Frappe Sign Request",
        {
            "certificate_signed_pdf_hash": pdf_hash,
        },
        "name",
    )

    if request_name:
        return {
            "request_name": request_name,
            "document_type": "certificate_signed_pdf",
            "matched_by": "Frappe Sign Request.certificate_signed_pdf_hash",
        }

    file_hash = frappe.db.get_value(
        "Frappe Sign File Hash",
        {
            "sha256_hash": pdf_hash,
            "hash_purpose": "Post-Sign",
        },
        ["frappe_sign_request", "file_url"],
        order_by="creation desc",
        as_dict=True,
    )

    if file_hash:
        return {
            "request_name": file_hash.frappe_sign_request,
            "document_type": "signed_pdf",
            "matched_by": "Frappe Sign File Hash Post-Sign",
            "file_url": file_hash.file_url,
        }

    file_hash = frappe.db.get_value(
        "Frappe Sign File Hash",
        {
            "sha256_hash": pdf_hash,
            "hash_purpose": "Verification",
        },
        ["frappe_sign_request", "file_url"],
        order_by="creation desc",
        as_dict=True,
    )

    if file_hash:
        return {
            "request_name": file_hash.frappe_sign_request,
            "document_type": "certificate_signed_pdf",
            "matched_by": "Frappe Sign File Hash Verification",
            "file_url": file_hash.file_url,
        }

    return None


def verify_stored_signed_pdf(request, uploaded_hash):
    if not request.signed_pdf:
        return {
            "passed": False,
            "message": "The matched request does not have a stored signed PDF.",
        }

    if not request.signed_pdf_hash:
        return {
            "passed": False,
            "message": "The matched request does not have a stored signed PDF hash.",
        }

    if request.signed_pdf_hash != uploaded_hash:
        return {
            "passed": False,
            "message": "The uploaded PDF hash does not match the request signed PDF hash.",
            "stored_hash": request.signed_pdf_hash,
            "uploaded_hash": uploaded_hash,
        }

    stored_hash = sha256_bytes(get_file_bytes(request.signed_pdf))

    if stored_hash != uploaded_hash:
        return {
            "passed": False,
            "message": "The stored signed PDF no longer matches its recorded hash.",
            "stored_file_hash": stored_hash,
            "recorded_hash": request.signed_pdf_hash,
            "uploaded_hash": uploaded_hash,
        }

    return {
        "passed": True,
        "message": "The uploaded PDF matches the final signed PDF stored for this request.",
        "stored_file": request.signed_pdf,
        "stored_hash": stored_hash,
    }


def verify_stored_certificate_signed_pdf(request, uploaded_hash):
    if not request.certificate_signed_pdf:
        return {
            "passed": False,
            "message": "The matched request does not have a stored certificate-signed PDF.",
        }

    if not request.certificate_signed_pdf_hash:
        return {
            "passed": False,
            "message": "The matched request does not have a stored certificate-signed PDF hash.",
        }

    if request.certificate_signed_pdf_hash != uploaded_hash:
        return {
            "passed": False,
            "message": "The uploaded PDF hash does not match the request certificate-signed PDF hash.",
            "stored_hash": request.certificate_signed_pdf_hash,
            "uploaded_hash": uploaded_hash,
        }

    stored_hash = sha256_bytes(get_file_bytes(request.certificate_signed_pdf))

    if stored_hash != uploaded_hash:
        return {
            "passed": False,
            "message": "The stored certificate-signed PDF no longer matches its recorded hash.",
            "stored_file_hash": stored_hash,
            "recorded_hash": request.certificate_signed_pdf_hash,
            "uploaded_hash": uploaded_hash,
        }

    return {
        "passed": True,
        "message": "The uploaded PDF matches the final certificate-signed PDF stored for this request.",
        "stored_file": request.certificate_signed_pdf,
        "stored_hash": stored_hash,
    }


def verify_certificate_bytes(request, uploaded_certificate_hash):
    if not request.audit_certificate:
        return {
            "passed": False,
            "message": "The matched request does not have an audit certificate.",
        }

    final_certificate_hash = get_latest_file_hash(
        request.name,
        request.audit_certificate,
        "Certificate",
    )

    if not final_certificate_hash:
        return {
            "passed": False,
            "message": "No stored certificate hash was found for this request.",
            "audit_certificate": request.audit_certificate,
        }

    stored_certificate_hash = sha256_bytes(get_file_bytes(request.audit_certificate))

    if stored_certificate_hash != final_certificate_hash:
        return {
            "passed": False,
            "message": "The stored audit certificate no longer matches the recorded certificate hash.",
            "audit_certificate": request.audit_certificate,
            "stored_certificate_hash": stored_certificate_hash,
            "recorded_certificate_hash": final_certificate_hash,
        }

    if uploaded_certificate_hash != final_certificate_hash:
        return {
            "passed": False,
            "message": "The uploaded certificate does not match the final audit certificate for this request.",
            "uploaded_certificate_hash": uploaded_certificate_hash,
            "recorded_certificate_hash": final_certificate_hash,
            "audit_certificate": request.audit_certificate,
        }

    return {
        "passed": True,
        "message": "The uploaded certificate matches the final audit certificate for this request.",
        "audit_certificate": request.audit_certificate,
        "certificate_hash": final_certificate_hash,
    }


def get_certificate_summary(request):
    if not request.audit_certificate:
        return {
            "available": False,
            "passed": False,
            "message": "No audit certificate is attached to this request.",
        }

    final_certificate_hash = get_latest_file_hash(
        request.name,
        request.audit_certificate,
        "Certificate",
    )

    if not final_certificate_hash:
        return {
            "available": True,
            "passed": False,
            "message": "An audit certificate is attached, but no certificate hash was found.",
            "audit_certificate": request.audit_certificate,
        }

    stored_hash = sha256_bytes(get_file_bytes(request.audit_certificate))

    return {
        "available": True,
        "passed": stored_hash == final_certificate_hash,
        "message": (
            "The stored audit certificate matches its recorded hash."
            if stored_hash == final_certificate_hash
            else "The stored audit certificate does not match its recorded hash."
        ),
        "audit_certificate": request.audit_certificate,
        "certificate_hash": final_certificate_hash,
        "stored_certificate_hash": stored_hash,
    }


def verify_audit_chain(request_name):
    events = frappe.get_all(
        "Frappe Sign Event",
        filters={
            "frappe_sign_request": request_name,
        },
        fields=[
            "name",
            "event_type",
            "previous_hash",
            "event_hash",
            "timestamp",
            "creation",
        ],
        order_by="timestamp asc, creation asc",
    )

    previous_hash = None

    for index, event in enumerate(events, start=1):
        if event.previous_hash != previous_hash:
            return {
                "passed": False,
                "message": f"Audit chain failed at event {index}. Previous hash does not match.",
                "event": event.name,
                "event_type": event.event_type,
                "expected_previous_hash": previous_hash,
                "actual_previous_hash": event.previous_hash,
            }

        if not event.event_hash:
            return {
                "passed": False,
                "message": f"Audit chain failed at event {index}. Event hash is missing.",
                "event": event.name,
                "event_type": event.event_type,
            }

        previous_hash = event.event_hash

    request_audit_chain_hash = frappe.db.get_value(
        "Frappe Sign Request",
        request_name,
        "audit_chain_hash",
    )

    if request_audit_chain_hash and previous_hash != request_audit_chain_hash:
        return {
            "passed": False,
            "message": "Audit chain head does not match the request audit chain hash.",
            "expected_audit_chain_hash": request_audit_chain_hash,
            "actual_final_event_hash": previous_hash,
        }

    return {
        "passed": True,
        "message": "The audit event chain is linked and matches the request audit chain hash.",
        "event_count": len(events),
        "final_event_hash": previous_hash,
    }


def calculate_event_hash(event, previous_hash):
    """
    This must mirror frappe_sign.utils.audit.append_event().

    If append_event() uses a different payload structure, update this function
    to match that exact structure.
    """
    payload = {
        "frappe_sign_request": event.frappe_sign_request if hasattr(event, "frappe_sign_request") else None,
        "event_type": event.event_type,
        "signer_email": event.signer_email,
        "user": event.user,
        "ip_address": event.ip_address,
        "user_agent": event.user_agent,
        "details_json": normalize_json(event.details_json),
        "document_hash": event.document_hash,
        "previous_hash": previous_hash,
        "timestamp": str(event.timestamp) if event.timestamp else None,
    }

    return sha256_bytes(
        json.dumps(
            payload,
            sort_keys=True,
            default=str,
            separators=(",", ":"),
        ).encode("utf-8")
    )


def normalize_json(value):
    if not value:
        return None

    try:
        return json.dumps(
            json.loads(value),
            sort_keys=True,
            default=str,
            separators=(",", ":"),
        )
    except Exception:
        return value


def get_latest_file_hash(request_name, file_url, hash_purpose=None):
    filters = {
        "frappe_sign_request": request_name,
        "file_url": file_url,
    }

    if hash_purpose:
        filters["hash_purpose"] = hash_purpose

    return frappe.db.get_value(
        "Frappe Sign File Hash",
        filters,
        "sha256_hash",
        order_by="creation desc",
    )


def build_request_summary(request):
    return {
        "name": request.name,
        "request_title": request.request_title,
        "status": request.status,
        "docstatus": request.docstatus,
        "source_type": request.source_type,
        "source_doctype": request.source_doctype,
        "source_name": request.source_name,
        "source_title": request.source_title,
        "signing_mode": request.signing_mode,
        "created_by": request.created_by,
        "creation": request.creation,
        "completed_on": request.completed_on,
        "signed_pdf": request.signed_pdf,
        "signed_pdf_hash": request.signed_pdf_hash,
        "audit_certificate": request.audit_certificate,
        "certificate_signed_pdf": request.certificate_signed_pdf,
        "certificate_signed_pdf_hash": request.certificate_signed_pdf_hash,
        "audit_chain_hash": request.audit_chain_hash,
        "tamper_status": request.tamper_status,
    }


def build_signer_summary(request):
    signers = []

    for signer in request.signers:
        if signer.role != "Signer":
            continue

        signers.append(
            {
                "full_name": signer.full_name,
                "email": signer.email,
                "status": signer.status,
                "signing_order": signer.signing_order,
                "viewed_on": signer.viewed_on,
                "signed_on": signer.signed_on,
                "declined_on": signer.declined_on,
            }
        )

    return signers